apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.DOMAIN_EMAIL}}
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: route53
        route53:
          region: eu-west-1
          hostedZoneID: {{.HOSTED_ZONE_ID}}
          accessKeyID: {{.ROUTE53_ACCESS_KEY_ID}}
          secretAccessKeySecretRef:
            name: cert-manager-route53
            key: secret-access-key